name: Google Cloud Function Deployment
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
    Deploy:
      name: Deploy
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: GCP Authentication
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: Debug GCP credentials
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS" > credentials.json
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: 'Use gcloud CLI'
        run: 'gcloud info'
      - name: 'Deploy a gen 2 cloud function'
        run: |
          gcloud functions deploy wechat \
            --region=asia-southeast2 \
            --allow-unauthenticated \
            --entry-point=wechat \
            --gen2 \
            --runtime=go122 \
            --trigger-http \
            --timeout=540s \
            --set-env-vars MONGOSTRING='${{ secrets.MONGOSTRING }}',JWT_SECRET='${{ secrets.JWT_SECRET }}
      - name: 'Cek eksistensi fungsi'
        run: 'gcloud functions describe wechat --region=asia-southeast2'
      - name: 'Cek log debugging'
        run: 'gcloud functions logs read wechat --region=asia-southeast2'
      - name: 'Cleaning Artifact Registry'
        run: 'gcloud artifacts repositories delete gcf-artifacts --location=asia-southeast2 --quiet'