name: Google Cloud Function Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PROJECT_ID: bagasip
  REGION: asia-southeast2
  FUNCTION_NAME: sakha
  ENTRY_POINT: sakha
  RUNTIME: go122
  RUNTIME_SA: renzip@bagasip.iam.gserviceaccount.com   # <<< pakai SA ini sebagai runtime

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to GCP with SA key
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Set project
        run: gcloud config set project $PROJECT_ID

      - name: Deploy Gen2 Cloud Function
        run: |
          gcloud functions deploy "$FUNCTION_NAME" \
            --project "$PROJECT_ID" \
            --region "$REGION" \
            --gen2 \
            --runtime "$RUNTIME" \
            --entry-point "$ENTRY_POINT" \
            --trigger-http \
            --allow-unauthenticated \
            --timeout 540s \
            --service-account renzip@bagasip.iam.gserviceaccount.com \
            --set-env-vars "MONGOSTRING=${{ secrets.MONGOSTRING }},JWT_SECRET=${{ secrets.JWT_SECRET }}"

      - name: Describe function
        run: gcloud functions describe "$FUNCTION_NAME" --region "$REGION"

      - name: Tail logs
        run: gcloud functions logs read "$FUNCTION_NAME" --region "$REGION" --limit=100
